@startuml Class_Examples


class Person {
    - firstName: String
    - lastName: String
    - birth: int
    + setBirth(int year): void
    + setFirstName(String name): void
    + setLastName(String name): void
    + info(): String
    + newInput(): void
}


class Student extends Person {
    - id: long
    + setId(long id): void
    + info(): String
}

class Lecturer extends Person {
    - department: String
    + info(): String
    + getDepartment(): String
    + setDepartment(String department): void
}

@enduml